# Generated by Django 4.1.6 on 2023-02-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='player',
        ),
        migrations.AddField(
            model_name='attendees',
            name='gamer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='levelupapi.gamer'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='A game!', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='number_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='levelupapi.Attendees', to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to='levelupapi.gamer'),
        ),
    ]
