# Generated by Django 4.1.6 on 2023-02-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_remove_attendees_player_attendees_gamer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number_players',
            new_name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
